# 配置演示说明（关于配置文件中状态的定义，最开始的定义都是up）

# ospf参考带宽，为了计算链路cost，参考带宽/链路带宽
ospfReferenceBandwidth: 10G

# 定义设备列表
devices:
  - id: core-1
    name: 核心路由器1
    role: core
    deviceType: router
    ip: 202.16.1.1
    netmask: 255.255.255.255
    status: up
    ospf: { area: 0 }
    interfaces:
      - { name: g0/0, ip: 10.0.0.1, netmask: 255.255.255.252, status: up }
      - { name: g0/1, ip: 10.0.0.5, netmask: 255.255.255.252, status: up }
      - { name: g0/2, ip: 10.0.0.9, netmask: 255.255.255.252, status: up }

# 定义链路列表，定义链路的源设备，源接口，目的设备，目的接口，状态，带宽
links:
  - {
      id: l1,
      srcDevice: core-1,
      srcInterface: g0/0,
      dstDevice: core-2,
      dstInterface: g0/0,
      status: up,
      bandwidth: 100G,
    }
