# 数据中心三层映射

ospfReferenceBandwidth: 10G

devices:
  - id: core-1
    name: 核心交换机-1
    role: core
    deviceType: router
    ip: 10.0.1.10
    netmask: 255.255.255.0
    status: up
    ospf: { routerId: 10.10.10.10, area: 0 }
    interfaces:
      - { name: g0/0, ip: 10.0.1.10, netmask: 255.255.255.252, status: up }
      - { name: g0/1, ip: 10.0.2.10, netmask: 255.255.255.252, status: up }

  - id: spine-1
    name: Spine交换机-1
    role: aggregation
    deviceType: switch
    ip: 10.0.0.1
    netmask: 255.255.255.0
    status: up
    ospf: { routerId: 1.1.1.1, area: 0 }
    interfaces:
      - { name: g0/0, ip: 10.0.1.1, netmask: 255.255.255.252, status: up }
      - {
          name: g0/1,
          ip: 10.0.1.5,
          netmask: 255.255.255.252,
          status: up,
          vlans: [10],
        }
      - {
          name: g0/2,
          ip: 10.0.1.17,
          netmask: 255.255.255.252,
          status: up,
          vlans: [20],
        }
      - {
          name: g0/3,
          ip: 10.0.1.13,
          netmask: 255.255.255.252,
          status: up,
          vlans: [30],
        }
      - {
          name: g0/4,
          ip: 10.0.1.5,
          netmask: 255.255.255.252,
          status: up,
          vlans: [40],
        }

  - id: spine-2
    role: aggregation
    name: Spine交换机-2
    deviceType: switch
    ip: 10.0.0.2
    netmask: 255.255.255.0
    status: up
    ospf: { routerId: 2.2.2.2, area: 0 }
    interfaces:
      - { name: g0/0, ip: 10.0.2.1, netmask: 255.255.255.252, status: up }
      - { name: g0/1, ip: 10.0.2.5, netmask: 255.255.255.252, status: up }
      - { name: g0/2, ip: 10.0.2.17, netmask: 255.255.255.252, status: up }
      - { name: g0/3, ip: 10.0.2.13, netmask: 255.255.255.252, status: up }
      - { name: g0/4, ip: 10.0.2.5, netmask: 255.255.255.252, status: up }

  - id: leaf-1
    name: Leaf交换机-1
    role: access
    deviceType: switch
    ip: 10.0.0.11
    netmask: 255.255.255.0
    status: up
    ospf: { routerId: 11.11.11.11, area: 1 }
    interfaces:
      - { name: g0/0, ip: 10.0.1.2, netmask: 255.255.255.252, status: up }
      - { name: g0/1, ip: 10.0.2.2, netmask: 255.255.255.252, status: up }
      - { name: g1/0, mode: access, vlans: [10], status: up }
      - { name: g1/1, mode: access, vlans: [10], status: up }
      - { name: g1/2, mode: access, vlans: [10], status: up }

  - id: leaf-2
    name: Leaf交换机-2
    role: access
    deviceType: switch
    ip: 10.0.0.12
    netmask: 255.255.255.0
    status: up
    ospf: { routerId: 12.12.12.12, area: 1 }
    interfaces:
      - { name: g0/0, ip: 10.0.1.6, netmask: 255.255.255.252, status: up }
      - { name: g0/1, ip: 10.0.2.6, netmask: 255.255.255.252, status: up }
      - { name: g1/0, mode: access, vlans: [20], status: up }
      - { name: g1/1, mode: access, vlans: [20], status: up }
      - { name: g1/2, mode: access, vlans: [20], status: up }

  - id: leaf-3
    name: Leaf交换机-3
    role: access
    deviceType: switch
    ip: 10.0.0.13
    netmask: 255.255.255.0
    status: up
    ospf: { routerId: 13.13.13.13, area: 2 }
    interfaces:
      - { name: g0/0, ip: 10.0.1.18, netmask: 255.255.255.252, status: up }
      - { name: g0/1, ip: 10.0.2.18, netmask: 255.255.255.252, status: up }
      - { name: g1/0, mode: access, vlans: [30], status: up }
      - { name: g1/1, mode: access, vlans: [30], status: up }
      - { name: g1/2, mode: access, vlans: [30], status: up }

  - id: leaf-4
    name: Leaf交换机-4
    role: access
    deviceType: switch
    ip: 10.0.0.14
    netmask: 255.255.255.0
    status: up
    ospf: { routerId: 14.14.14.14, area: 2 }
    interfaces:
      - { name: g0/0, ip: 10.0.1.14, netmask: 255.255.255.252, status: up }
      - { name: g0/1, ip: 10.0.2.14, netmask: 255.255.255.252, status: up }
      - { name: g1/0, mode: access, vlans: [40], status: up }
      - { name: g1/1, mode: access, vlans: [40], status: up }
      - { name: g1/2, mode: access, vlans: [40], status: up }

  - id: server-1
    name: 服务器-1
    role: terminal
    deviceType: server
    ip: 192.168.10.10
    netmask: 255.255.255.0
    gateway: 192.168.10.1
    status: up
    interfaces:
      - {
          name: eth0,
          ip: 192.168.10.10,
          netmask: 255.255.255.0,
          vlans: [10],
          status: up,
        }

  - {
      id: server-2,
      name: 服务器-2,
      role: terminal,
      deviceType: server,
      ip: 192.168.10.11,
      netmask: 255.255.255.0,
      gateway: 192.168.10.1,
      status: up,
      interfaces:
        [
          {
            name: eth0,
            ip: 192.168.10.11,
            netmask: 255.255.255.0,
            vlans: [10],
            status: up,
          },
        ],
    }
  - {
      id: server-3,
      name: 服务器-3,
      role: terminal,
      deviceType: server,
      ip: 192.168.10.12,
      netmask: 255.255.255.0,
      gateway: 192.168.10.1,
      status: up,
      interfaces:
        [
          {
            name: eth0,
            ip: 192.168.10.12,
            netmask: 255.255.255.0,
            vlans: [10],
            status: up,
          },
        ],
    }

  - {
      id: server-4,
      name: 服务器-4,
      role: terminal,
      deviceType: server,
      ip: 192.168.20.10,
      netmask: 255.255.255.0,
      gateway: 192.168.20.1,
      status: up,
      interfaces:
        [
          {
            name: eth0,
            ip: 192.168.20.10,
            netmask: 255.255.255.0,
            vlans: [20],
            status: up,
          },
        ],
    }
  - {
      id: server-5,
      name: 服务器-5,
      role: terminal,
      deviceType: server,
      ip: 192.168.20.11,
      netmask: 255.255.255.0,
      gateway: 192.168.20.1,
      status: up,
      interfaces:
        [
          {
            name: eth0,
            ip: 192.168.20.11,
            netmask: 255.255.255.0,
            vlans: [20],
            status: up,
          },
        ],
    }
  - {
      id: server-6,
      name: 服务器-6,
      role: terminal,
      deviceType: server,
      ip: 192.168.20.12,
      netmask: 255.255.255.0,
      gateway: 192.168.20.1,
      status: up,
      interfaces:
        [
          {
            name: eth0,
            ip: 192.168.20.12,
            netmask: 255.255.255.0,
            vlans: [20],
            status: up,
          },
        ],
    }

  - {
      id: server-7,
      name: 服务器-7,
      role: terminal,
      deviceType: server,
      ip: 192.168.30.10,
      netmask: 255.255.255.0,
      gateway: 192.168.30.1,
      status: up,
      interfaces:
        [
          {
            name: eth0,
            ip: 192.168.30.10,
            netmask: 255.255.255.0,
            vlans: [30],
            status: up,
          },
        ],
    }
  - {
      id: server-8,
      name: 服务器-8,
      role: terminal,
      deviceType: server,
      ip: 192.168.30.11,
      netmask: 255.255.255.0,
      gateway: 192.168.30.1,
      status: up,
      interfaces:
        [
          {
            name: eth0,
            ip: 192.168.30.11,
            netmask: 255.255.255.0,
            vlans: [30],
            status: up,
          },
        ],
    }
  - {
      id: server-9,
      name: 服务器-9,
      role: terminal,
      deviceType: server,
      ip: 192.168.30.12,
      netmask: 255.255.255.0,
      gateway: 192.168.30.1,
      status: up,
      interfaces:
        [
          {
            name: eth0,
            ip: 192.168.30.12,
            netmask: 255.255.255.0,
            vlans: [30],
            status: up,
          },
        ],
    }

  - {
      id: server-10,
      name: 服务器-10,
      role: terminal,
      deviceType: server,
      ip: 192.168.40.10,
      netmask: 255.255.255.0,
      gateway: 192.168.40.1,
      status: up,
      interfaces:
        [
          {
            name: eth0,
            ip: 192.168.40.10,
            netmask: 255.255.255.0,
            vlans: [40],
            status: up,
          },
        ],
    }
  - {
      id: server-11,
      name: 服务器-11,
      role: terminal,
      deviceType: server,
      ip: 192.168.40.11,
      netmask: 255.255.255.0,
      gateway: 192.168.40.1,
      status: up,
      interfaces:
        [
          {
            name: eth0,
            ip: 192.168.40.11,
            netmask: 255.255.255.0,
            vlans: [40],
            status: up,
          },
        ],
    }
  - {
      id: server-12,
      name: 服务器-12,
      role: terminal,
      deviceType: server,
      ip: 192.168.40.12,
      netmask: 255.255.255.0,
      gateway: 192.168.40.1,
      status: up,
      interfaces:
        [
          {
            name: eth0,
            ip: 192.168.40.12,
            netmask: 255.255.255.0,
            vlans: [40],
            status: up,
          },
        ],
    }

links:
  - {
      id: l1,
      srcDevice: spine-1,
      srcInterface: g0/1,
      dstDevice: leaf-1,
      dstInterface: g0/0,
      bandwidth: 10G,
      status: up,
    }
  - {
      id: l2,
      srcDevice: spine-2,
      srcInterface: g0/0,
      dstDevice: leaf-1,
      dstInterface: g0/1,
      bandwidth: 10G,
      status: up,
    }

  - {
      id: l3,
      srcDevice: spine-1,
      srcInterface: g0/2,
      dstDevice: leaf-2,
      dstInterface: g0/0,
      bandwidth: 10G,
      status: up,
    }
  - {
      id: l4,
      srcDevice: spine-2,
      srcInterface: g0/1,
      dstDevice: leaf-2,
      dstInterface: g0/1,
      bandwidth: 10G,
      status: up,
    }

  - {
      id: l5,
      srcDevice: spine-1,
      srcInterface: g0/3,
      dstDevice: leaf-3,
      dstInterface: g0/0,
      bandwidth: 10G,
      status: up,
    }
  - {
      id: l6,
      srcDevice: spine-2,
      srcInterface: g0/2,
      dstDevice: leaf-3,
      dstInterface: g0/1,
      bandwidth: 10G,
      status: up,
    }

  - {
      id: l7,
      srcDevice: spine-1,
      srcInterface: g0/4,
      dstDevice: leaf-4,
      dstInterface: g0/0,
      bandwidth: 10G,
      status: up,
    }
  - {
      id: l8,
      srcDevice: spine-2,
      srcInterface: g0/3,
      dstDevice: leaf-4,
      dstInterface: g0/1,
      bandwidth: 10G,
      status: up,
    }

  - {
      id: l9,
      srcDevice: leaf-1,
      srcInterface: g1/0,
      dstDevice: server-1,
      dstInterface: eth0,
      status: up,
      bandwidth: 1G,
    }
  - {
      id: l10,
      srcDevice: leaf-1,
      srcInterface: g1/1,
      dstDevice: server-2,
      dstInterface: eth0,
      status: up,
      bandwidth: 1G,
    }
  - {
      id: l11,
      srcDevice: leaf-1,
      srcInterface: g1/2,
      dstDevice: server-3,
      dstInterface: eth0,
      status: up,
      bandwidth: 1G,
    }

  - {
      id: l12,
      srcDevice: leaf-2,
      srcInterface: g1/0,
      dstDevice: server-4,
      dstInterface: eth0,
      status: up,
      bandwidth: 1G,
    }
  - {
      id: l13,
      srcDevice: leaf-2,
      srcInterface: g1/1,
      dstDevice: server-5,
      dstInterface: eth0,
      status: up,
      bandwidth: 1G,
    }
  - {
      id: l14,
      srcDevice: leaf-2,
      srcInterface: g1/2,
      dstDevice: server-6,
      dstInterface: eth0,
      status: up,
      bandwidth: 1G,
    }

  - {
      id: l15,
      srcDevice: leaf-3,
      srcInterface: g1/0,
      dstDevice: server-7,
      dstInterface: eth0,
      status: up,
      bandwidth: 1G,
    }
  - {
      id: l16,
      srcDevice: leaf-3,
      srcInterface: g1/1,
      dstDevice: server-8,
      dstInterface: eth0,
      status: up,
      bandwidth: 1G,
    }
  - {
      id: l17,
      srcDevice: leaf-3,
      srcInterface: g1/2,
      dstDevice: server-9,
      dstInterface: eth0,
      status: up,
      bandwidth: 1G,
    }

  - {
      id: l18,
      srcDevice: leaf-4,
      srcInterface: g1/0,
      dstDevice: server-10,
      dstInterface: eth0,
      status: up,
      bandwidth: 1G,
    }
  - {
      id: l19,
      srcDevice: leaf-4,
      srcInterface: g1/1,
      dstDevice: server-11,
      dstInterface: eth0,
      status: up,
      bandwidth: 1G,
    }
  - {
      id: l20,
      srcDevice: leaf-4,
      srcInterface: g1/2,
      dstDevice: server-12,
      dstInterface: eth0,
      bandwidth: 1G,
      status: up,
    }
  - {
      id: l21,
      srcDevice: core-1,
      srcInterface: g0/0,
      dstDevice: spine-1,
      dstInterface: g0/0,
      bandwidth: 10G,
      status: up,
    }
  - {
      id: l22,
      srcDevice: core-1,
      srcInterface: g0/1,
      dstDevice: spine-2,
      dstInterface: g0/0,
      bandwidth: 10G,
      status: up,
    }
